### ISSUE TITLE
Unable to install units npm package due to packages in devDependencies

### ISSUE THREAD

**Issue by darrenyung** [stak-digital/units#12]
There are still some package such 'title-case' that needed during post-install but still in devDependancies.

**Comment by brycehanscomb** [comment]
Can you suggest what actions need to be taken to fix this?

**Comment by darrenyung** [comment]
This is the error I'm facing when trying to install the package.

`npm install @stak-digital/units --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\Darren\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '@stak-digital/units',
npm verb cli   '--verbose' ]
npm info using npm@6.9.0
npm info using node@v10.16.0
npm verb npm-session 9bd3e1958b96ac87
npm http fetch GET 200 https://registry.npmjs.org/@stak-digital%2funits 1852ms
npm timing stage:loadCurrentTree Completed in 1940ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 7ms
npm timing stage:loadIdealTree Completed in 12ms
npm timing stage:generateActionsToTake Completed in 6ms
npm verb correctMkdir C:\Users\Darren\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\Darren\AppData\Roaming\npm-cache\_locks\staging-1966327faaef6bed.lock for F:\Work\Prototype\stak\node_modules\.staging
[       ...........] | extract:@stak-digital/units: verb lock using C:\Users\Darren\AppData\Roaming\npm-cache\_locks\stanpm timing audit submit Completed in 570ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 571ms
npm timing audit body Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/@stak-digital/units/-/units-1.10.2.tgz 627ms
npm timing action:extract Completed in 1053ms
npm timing action:finalize Completed in 8ms
npm timing action:refresh-package-json Completed in 38ms
npm info lifecycle @stak-digital/units@1.10.2~preinstall: @stak-digital/units@1.10.2
npm timing action:preinstall Completed in 2ms
npm info linkStuff @stak-digital/units@1.10.2
npm timing action:build Completed in 1ms
npm info lifecycle @stak-digital/units@1.10.2~install: @stak-digital/units@1.10.2
npm timing action:install Completed in 1ms
npm info lifecycle @stak-digital/units@1.10.2~postinstall: @stak-digital/units@1.10.2

> @stak-digital/units@1.10.2 postinstall F:\Work\Prototype\stak\node_modules\@stak-digital\units
> npm run all

npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'prefix',
npm verb cli   '-g' ]
npm info using npm@6.9.0
npm info using node@v10.16.0
npm verb exit [ 0, true ]
npm timing npm Completed in 109ms
npm info ok
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\Darren\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'all' ]
npm info using npm@6.9.0
npm info using node@v10.16.0
npm verb run-script [ 'preall', 'all', 'postall' ]
npm info lifecycle @stak-digital/units@1.10.2~preall: @stak-digital/units@1.10.2
npm info lifecycle @stak-digital/units@1.10.2~all: @stak-digital/units@1.10.2

> @stak-digital/units@1.10.2 all F:\Work\Prototype\stak\node_modules\@stak-digital\units
> node scripts/units.js && npm run build && npm run docs && npm run build:demo

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (F:\Work\Prototype\stak\node_modules\@stak-digital\units\scripts\units.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

2 suggestions I could think of:

1. Update package.json and move 3rd party packages from devDependency into dependency.
2. Rollback code to previous version as the package before installs without issues.

**Comment by 3stacks** [comment]
Hi, could you try installing at version 1.10.3? This should be working, I've just tested it locally.

**Comment by darrenyung** [comment]
Yep, works fine now. Thanks!
